# Generated by Django 6.0.2 on 2026-02-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('capuchin', models.IntegerField(default=0)),
                ('dominican', models.IntegerField(default=0)),
                ('benedictine', models.IntegerField(default=0)),
                ('carmelite', models.IntegerField(default=0)),
                ('augustinian', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discernment.question')),
            ],
        ),
    ]
