# Generated by Django 6.0.2 on 2026-02-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discernment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('values', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('icon', models.CharField(default='heart', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharismDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CharismScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('charism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='discernment.charism')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='discernment.charismdimension')),
            ],
            options={
                'ordering': ['dimension__order', 'charism__name'],
                'unique_together': {('charism', 'dimension')},
            },
        ),
    ]
